title: Varsharani Dhupadale
author: Varsharani 
email: varsharani.oct9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi everyone ! I am working as a software engineer and learning GitHub pages for my project for documentation.

# social links
twitter_username: VD075248 # DO NOT include the @ character, or else the build will fail!
github_username:  VD075248 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate

